"""Price-aware control logic (control.py) + actrl wiring (docs/pricing.md).

The warmup parity fixture was generated by running the VALIDATED analysis
implementation (analysis/warmup_shift.py coarse_costs/decide) on a
synthetic morning -- scratch script, 2026-07-07: day starts 00:00 local,
decision 00:30, deadline 7.5 local (7.0 h from decision), t_day 19.7,
t_bulk0 18.2, Tout 4.0, retail = wholesale/1000*2.2 + 0.05, flat 100 $/MWh
with a 2000 $/MWh spike 06:00-08:00 local. The control.py port must
reproduce those numbers exactly (times there are LOCAL hh; control.py
works in hours from the decision instant, hence the -0.5 shift).
"""
import math

import pytest

import control
from control import (
    interp_knots,
    price_pressure_offset,
    warmup_decide,
    warmup_expected_costs,
    warmup_glambda,
)

import hvac_harness  # noqa: F401  (stubs hassapi before importing actrl)
import actrl
import scenarios


# --- fixture from analysis/warmup_shift.py (see module docstring) ---------

ANALYSIS_COSTS_LOCAL_HH = {
    1.0: 5.801774916349577,
    1.5: 5.7628735337935115,
    2.0: 5.72200705697996,
    2.5: 5.679171735633492,
    3.0: 5.63436380873263,
    3.5: 5.587579504468749,
    4.0: 11.241580109576164,
    4.5: 16.865027356787216,
    5.0: 22.45786265714681,
    5.5: float("inf"),
    6.0: float("inf"),
    6.5: float("inf"),
    7.0: float("inf"),
}
ANALYSIS_DECISION = (3.5, 5.0, 1.5)  # (t_star, t_jit, shift) local hh


def _synthetic_prices(spike=True):
    """(hours_from_decision, retail) half-hours, matching the fixture."""
    out = []
    for i in range(25):  # 00:00 .. 12:00 local
        hh = i * 0.5
        rrp = 2000.0 if spike and 6.0 <= hh < 8.0 else 100.0
        out.append((hh - 0.5, rrp / 1000.0 * 2.2 + 0.05))
    return out


def test_warmup_costs_match_analysis_implementation():
    prices = {h: warmup_glambda(p) for h, p in _synthetic_prices()}

    def price_at(h):
        best = None
        for gh in sorted(prices):
            if gh <= h:
                best = prices[gh]
        return best if best is not None else prices[min(prices)]

    candidates = [hh - 0.5 for hh in ANALYSIS_COSTS_LOCAL_HH]
    costs = warmup_expected_costs(
        candidates, price_at, 4.0, 7.0, 18.2, 19.7
    )
    for hh, expected in ANALYSIS_COSTS_LOCAL_HH.items():
        got = costs[hh - 0.5]
        if math.isinf(expected):
            assert math.isinf(got), hh
        else:
            assert got == pytest.approx(expected, rel=1e-12), hh


def test_warmup_decide_matches_analysis_decision():
    d = warmup_decide(_synthetic_prices(), 4.0, 7.0, 18.2, 19.7)
    assert d is not None
    t_star, t_jit, shift = d
    assert t_star == pytest.approx(ANALYSIS_DECISION[0] - 0.5)
    assert t_jit == pytest.approx(ANALYSIS_DECISION[1] - 0.5)
    assert shift == pytest.approx(ANALYSIS_DECISION[2])


def test_warmup_decide_flat_prices_stays_just_in_time():
    d = warmup_decide(_synthetic_prices(spike=False), 4.0, 7.0, 18.2, 19.7)
    assert d is not None
    assert d[2] == 0.0


def test_warmup_decide_degrades_to_none():
    assert warmup_decide([], 4.0, 7.0, 18.2, 19.7) is None
    # deadline too close to plan anything
    assert warmup_decide(_synthetic_prices(), 4.0, 0.5, 18.2, 19.7) is None


# --- continuous price offset ----------------------------------------------

def test_interp_knots_clamps_and_interpolates():
    xs, ys = [1.0, 2.0, 4.0], [10.0, 20.0, 40.0]
    assert interp_knots(0.0, xs, ys) == 10.0
    assert interp_knots(9.0, xs, ys) == 40.0
    assert interp_knots(3.0, xs, ys) == pytest.approx(30.0)


def test_price_offset_no_data_is_zero():
    assert price_pressure_offset(0.30, []) == 0.0
    # entries outside (0, horizon] are ignored
    assert price_pressure_offset(0.30, [(-1.0, 5.0), (9.0, 5.0)]) == 0.0


def test_price_offset_flat_prices_near_zero():
    # flat prices: retention discount and the mild E[actual|fc] uplift
    # nearly cancel -- no meaningful pressure either way
    flat = [(h * 0.5, 0.25) for h in range(1, 16)]
    off = price_pressure_offset(0.25, flat)
    assert abs(off) < 0.05


def test_price_offset_spike_ahead_banks():
    # $2/kWh forecast in 3 h vs $0.25 now. The APF knots clamp at the top
    # bin (the p50 model never forecasts that high), so the bank is the
    # top-knot value under retention, not the hard clamp.
    off = price_pressure_offset(0.25, [(3.0, 2.0)])
    expected = control.price_offset_k * (
        control.fc_knots_e_actual[-1] * math.exp(-3.0 / 20.0) - 0.25
    )
    assert off == pytest.approx(expected)
    assert 0.5 < off < control.price_bank_max_k


def test_price_offset_expensive_now_shaves_to_clamp():
    off = price_pressure_offset(5.0, [(1.0, 0.20)])
    assert off == -control.price_shave_max_k


# --- actrl wiring (harness) -------------------------------------------------

def _price_world(now_price, forecast_prices):
    """Heat-mode world with the price entities present and enabled."""
    import datetime

    targets = {r: (20.0, 24.0) for r in scenarios.ROOMS}
    temps = {r: 18.0 for r in scenarios.ROOMS}
    world = scenarios.base_world(climate_state="heat", setpoint=17.0)
    scenarios.room_climates(world, "heat_cool", targets, temps)
    now = datetime.datetime.now(datetime.timezone.utc)
    value_key = actrl.price_forecast_entity.split(".", 1)[1]
    forecasts = [
        {
            "date": (now + datetime.timedelta(hours=h)).isoformat(),
            value_key: p,
        }
        for h, p in forecast_prices
    ]
    world["input_boolean.ac_use_price_pressure"] = {"state": "on"}
    world[actrl.price_now_entity] = {"state": str(now_price)}
    world[actrl.price_forecast_entity] = {
        "state": str(now_price),
        "attributes": {actrl.price_forecast_attr: forecasts},
    }
    return world


def _run_cycles(world, cycles=3):
    from unittest import mock

    w = hvac_harness.FakeWorld(world)
    app = hvac_harness.HarnessActrl(w)
    with mock.patch.object(actrl.time, "sleep", lambda s: None):
        app.initialize()
        for cycle in range(cycles):
            w.cycle = cycle
            app.main({})
    return w, app


def test_actrl_price_pressure_banks_on_spike_forecast():
    world = _price_world(0.25, [(3.0, 2.0)])
    w, app = _run_cycles(world)
    # offset metric published; expected bank = top-knot value under
    # retention (see test_price_offset_spike_ahead_banks), inside the
    # 1.0 K room bound (grid_surplus_max_heating 21 vs target 20)
    expected = control.price_offset_k * (
        control.fc_knots_e_actual[-1] * math.exp(-3.0 / 20.0) - 0.25
    )
    metric = float(w.entities["input_number.aircon_price_pressure"]["state"])
    assert metric == pytest.approx(expected, abs=0.01)
    # heating demand includes the bank: demand = (20 - 18) + bank
    err = float(w.entities["input_number.aircon_weighted_error"]["state"])
    assert err == pytest.approx(-(2.0 + min(expected, 1.0)), abs=0.05)


def test_actrl_price_pressure_shave_reduces_demand():
    world = _price_world(5.0, [(1.0, 0.20)])
    w, app = _run_cycles(world)
    metric = float(w.entities["input_number.aircon_price_pressure"]["state"])
    assert metric == pytest.approx(-control.price_shave_max_k)
    err = float(w.entities["input_number.aircon_weighted_error"]["state"])
    assert err == pytest.approx(-(2.0 - 0.75), abs=0.05)


def test_actrl_price_pressure_off_or_missing_is_inert():
    # boolean absent entirely (the goldens' world): no metric write, no
    # demand change vs an explicit baseline
    targets = {r: (20.0, 24.0) for r in scenarios.ROOMS}
    temps = {r: 18.0 for r in scenarios.ROOMS}
    base = scenarios.base_world(climate_state="heat", setpoint=17.0)
    scenarios.room_climates(base, "heat_cool", targets, temps)
    w_base, _ = _run_cycles(dict(base))
    assert "input_number.aircon_price_pressure" not in w_base.entities

    # boolean on but price entities missing: offset 0, demand unchanged
    on = dict(base)
    on["input_boolean.ac_use_price_pressure"] = {"state": "on"}
    w_on, _ = _run_cycles(on)
    assert float(
        w_on.entities["input_number.aircon_price_pressure"]["state"]
    ) == 0.0
    assert (
        w_on.entities["input_number.aircon_weighted_error"]["state"]
        == w_base.entities["input_number.aircon_weighted_error"]["state"]
    )
